[package]
name = "certspook"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
libbpf-rs = "0.21.1"
libc = "0.2.147"
plain = "0.2.3"

[build-dependencies]
libbpf-cargo = "0.21.1"
